### PR TITLE
Fix automatic project import in Android Studio/IntelliJ.

### PR DESCRIPTION
**Pull request by pawelkw**
So I tried to import your project and failed multiple times.

Added this and it solved everything.

### CODE REVIEW

**Comment by jaredsburrows** [comment]
@pawelkw You failed to import it because you were clicking the `build.gradle.kts` file directly. You only have to click on the top "folder" of the project when importing.

**Comment by pawelkw** [comment]
@jaredsburrows Nope. I tried "Open" on folder level as well as the build file. Also tried "Import" for the same stuff. Didn't work. Android Studio 3.0 Beta 2.

**Comment by jaredsburrows** [comment]
@pawelkw Can you please be consistent and use `"` quotes and use `setBuildFileName`?
 I am preparing this for Kotlin. Like this: `rootProject.setBuildFileName("build.gradle.kts")`

**Comment by jaredsburrows** [comment]
Thanks.

**Comment by jaredsburrows** [comment]
@pawelkw Sorry to be picky, but can you make the code consistent? Like this:

```
rootProject.setName("android-gif-example")
rootProject.setBuildFileName("build.gradle.kts")
```

**Pull request merged**
