### PR TITLE
apply 3.0 plugin

### PR DESCRIPTION
**Pull request by jaredsburrows**
TODO
 - Lint: `MissingRegistered`
 - Dependency Resolution: Jacoco `0.7.4.201502262128`
 - Put `tasks.withType<KotlinCompile>` in separate file?
 
Java 8

### CODE REVIEW

**Comment by jaredsburrows** [comment]
Latest build failure: https://issuetracker.google.com/issues/63950135

**Comment by pawelkw** [comment]
`lintDebug` works for me. What's the issue here?

**Comment by jaredsburrows** [comment]
@pawelkw It is this issue: https://github.com/jaredsburrows/android-gif-example/pull/12/files#diff-392475fdf2bc320d17762ed97109a121R101. "MissingRegistered".

**Comment by pawelkw** [comment]
oh

**Comment by pawelkw** [comment]
IMHO just add 
```
  <issue id="MissingRegistered" severity="ignore"/>
```
to `lint.xml`, link to the issue and live with it for now. From previous experience bugs like these can take years to fix. :)

**Comment by jaredsburrows** [comment]
@pawelkw Yeah. There are just other problems with the plugin as well.

**Comment by jaredsburrows** [comment]
@pawelkw Yeah. Google is taking forever to release this plugin. I may just have to merge this.

**Pull request merged**
